import Motion from './motion';
import { ArrowDown, ArrowUpRight, ArrowRight, Crosshair, Globe2, Mail, Code, BriefcaseBusiness } from 'lucide-react';
const projects = [
  {name:'QuickDrop',image:'/images/quickdrop-orbit.webp',description:'I built QuickDrop to share files through short-lived sessions, with separate AWS and GCP setups. In testing, a 500 MB transfer took about 50 seconds on local Wi-Fi.',tags:['FULL STACK','AWS / GCP'],href:'https://quickdrop-9a015.web.app/'},
  {name:'UTA Datathon',image:'/images/datathon-base.webp',description:'I built the registration and QR check-in platform for UTA Datathon. It handled 400+ participants and cut check-in from about a minute to 10 seconds.',tags:['NEXT.JS','FIREBASE'],href:'https://famous-lily-a54f63.netlify.app/'},
  {name:'Map Daddy',image:'/images/map-daddy-lander.webp',description:'Map Daddy lets you control projections from a browser while a Raspberry Pi handles playback. You can adjust the corners to fit the surface you’re projecting onto.',tags:['RASPBERRY PI','CREATIVE TECH'],href:'https://github.com/thatscrazzyy/map-daddy'},
];
export default function Home(){return <main id="top" className="portfolio"><Motion/>
<a className="skip-link" href="#projects">Skip to projects</a>
<section className="hero"><img className="hero-image" src="/images/space-background.webp" alt="" fetchPriority="high" width="3240" height="5760"/><div className="hero-scene"><img className="astronaut-layer" src="/images/astronaut-layer.webp" alt="An astronaut tethered to a spacecraft, floating in space" width="3240" height="5760"/></div>
<nav aria-label="Main navigation"><div className="nav-links"><a href="#top">HOME</a><a href="#about">ABOUT</a><a href="#projects">PROJECTS</a><a href="#experience">EXPERIENCE</a><a href="#contact">CONTACT</a></div><Crosshair className="nav-mark" size={30}/></nav>
<div className="hero-content"><p className="hero-kicker mono">SOFTWARE · SOLUTIONS · STORIES</p><h1><span>SAMARTH</span><span>JAGTAP.</span></h1><p className="intro">I build software that helps people<br className="desktop-break"/> get their work done.</p><p className="hero-description mono">SOFTWARE ENGINEERING SENIOR AT UT ARLINGTON.<br/>WORKING ON CLOUD APPS AND AI TOOLS.<br/>STUDYING FILMMAKING ALONG THE WAY.</p><a className="scroll-link mono" href="#projects"><ArrowDown size={28} strokeWidth={1}/><span>SCROLL TO<br/>EXPLORE THE WORK</span></a></div><span className="hero-note mono">SAME CHAOS.<br/>BIGGER IDEAS.<span className="plus">＋</span></span>
</section><div className="status-strip mono"><Globe2 size={28}/><span><small>CURRENTLY:</small>BUILDING COOL THINGS.</span><span className="location"><small>BASED IN:</small>DALLAS-FORT WORTH, TX</span><i className="barcode" aria-hidden="true"/></div>
<section id="projects" className="projects"><div className="eyebrow mono"><span>01.</span><a href="https://github.com/thatscrazzyy" target="_blank" rel="noreferrer">VIEW GITHUB <ArrowRight size={16}/></a></div><h2 className="featured-title">FEATURED PROJECTS</h2><div className="project-list">{projects.map((p,i)=><a key={p.name} className={'project project-'+i} href={p.href} target="_blank" rel="noreferrer"><span className="project-number mono">0{i+1}</span><div className="project-art"><img src={p.image} alt="" loading="lazy" width="1536" height="1024"/><span className="art-cross">+</span></div><div className="project-info"><h3>{p.name}</h3><p className="mono">{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div><ArrowUpRight className="project-arrow" size={29} strokeWidth={1.5}/></a>)}</div></section>
<section className="selected-work" id="selected-work"><div className="section-heading"><span className="mono">02.</span><h2>MORE EXPLORATIONS</h2><a className="meta mono" href="https://github.com/thatscrazzyy" target="_blank" rel="noreferrer">MORE PROJECTS <ArrowRight size={15}/></a></div><div className="work-grid">
<a href="https://igvc-web.vercel.app/" target="_blank" rel="noreferrer" className="work-tile"><div className="tile-image lunar"/><h3 className="mono">01. AUTONOMY</h3><p className="mono">ROBOTICS / VISION</p></a>
<a href="https://github.com/thatscrazzyy/map-daddy" target="_blank" rel="noreferrer" className="work-tile"><div className="tile-image red"/><h3 className="mono">02. MAP DADDY</h3><p className="mono">CREATIVE TECHNOLOGY</p></a>
<a href="https://quickdrop-9a015.web.app/" target="_blank" rel="noreferrer" className="work-tile"><div className="tile-image closeup"/><h3 className="mono">03. QUICKDROP</h3><p className="mono">CLOUD / FULL STACK</p></a>
<a href="#sidequest" className="work-tile"><div className="tile-image green"/><h3 className="mono">04. SIDEQUEST</h3><p className="mono">iOS / SOCIAL PLAY</p></a>
</div><details id="sidequest" className="sidequest"><summary className="mono">SIDEQUEST: PLANS WITH FRIENDS <span>+</span></summary><p>SideQuest is an iMessage prototype for sending friends small challenges, from a food run to a study session. I built it with Swift, UIKit, and Firebase, then tested it with 10 friends. Quests have five states, with updates arriving in real time. It isn’t publicly released yet.</p></details></section>
<div className="quote-strip"><div><span className="quote-mark">”</span><p className="mono">I STUDY SOFTWARE<br/>ENGINEERING AND<br/>COMMERCIAL FILMMAKING.<br/><br/>THERE’S USUALLY<br/>MORE THAN ONE PROJECT<br/>ON MY DESK.</p></div><div className="quote-image"/><p className="mono quote-aside">IDEAS<br/>CODE<br/>PEOPLE<br/>SYSTEMS<br/>AND<br/>BEYOND.<span>✧</span></p></div><section id="about" className="about"><div className="section-heading"><span className="mono">03.</span><h2>ABOUT</h2><span className="meta mono">PEOPLE × IDEAS × SYSTEMS</span></div><div className="about-body"><div className="about-art"/><div><h3>A BIT<br/>ABOUT ME.</h3><p>I’m finishing my software engineering degree at UT Arlington in December 2026. I also study commercial filmmaking, and I founded Dastaan, our Bollywood fusion dance team.</p><p>I build tools that help people with real operational work. I spend time understanding the problem before writing code, whether that means cleaning up inventory records, replacing an old application, or deploying an AI tool.</p><p>I’m interested in forward deployed and solutions engineering roles. I like working with the people who use what I build, explaining the tradeoffs, and staying involved when it’s time to put the software to use.</p><div className="education"><h3>EDUCATION</h3><p>B.S. in Software Engineering<br/>University of Texas at Arlington</p><span className="mono">Minor in Commercial Filmmaking · Expected December 2026</span></div><a className="outline-link mono" href="#experience">MY EXPERIENCE <ArrowRight size={18}/></a></div><div className="explore-panel"><span>✧</span><Globe2 size={65} strokeWidth={.6}/><p className="mono">EXPLORE<br/>LEARN<br/>BUILD</p></div></div></section>
<section id="experience" className="experience"><div className="section-heading"><span className="mono">04.</span><h2>EXPERIENCE</h2></div>
<h3 className="experience-group">Work</h3>
<article className="experience-entry"><header><div><h3>Software / AI Intern</h3><p className="mono">Software and AI internship</p></div><span className="role-date mono">March 2026 to present</span></header><ul><li>I built an inventory tool with Vite, Node.js, and PostgreSQL for more than 200,000 records.</li><li>Queries became 45% faster, and the team saved roughly 15 hours of manual work a week.</li><li>Vendor comparisons and bulk duplicate cleanup helped employees review work in hours that had previously taken days.</li><li>I helped migrate two legacy HTML/PHP applications in four weeks against an estimated six-month timeline.</li><li>I converted web apps into Electron desktop apps for more than 300 daily users, giving them offline access to local hardware.</li><li>For a live customer Odoo environment, I deployed MCP-powered agents with scoped access, approval steps, audit logs, and rollback.</li></ul></article>
<article className="experience-entry"><header><div><h3>Teaching Assistant</h3><p className="mono">UT Arlington · College of Engineering</p></div><span className="role-date mono">August 2025 to present</span></header><ul><li>I support ENGR 1101, which serves about 400 students each semester.</li><li>A Python script I wrote processes 400 assignments in under four minutes and prepares the results for Canvas.</li><li>The workflow saves over two hours per grading batch.</li><li>I work with the teaching staff on consistent grading and student support.</li></ul></article>
<article className="experience-entry"><header><div><h3>LEGO FIRST League Coach / Camp Counselor</h3><p className="mono">Kids &amp; Teens University · UT Arlington</p></div><span className="role-date mono">May 2025 to August 2025</span></header><ul><li>I taught engineering and robotics across more than 10 summer camps serving 500+ middle and high school students.</li><li>Students worked on robot design, programming, and testing.</li><li>I made the concepts approachable and helped students work through problems together.</li></ul></article>
<details className="role-dropdown"><summary className="mono">SHOW MORE WORK EXPERIENCE <span>+</span></summary><div className="more-role-list"><p><strong>Resident Assistant</strong><br/>Supported 38 residents and helped run 12 residential events at University Housing.</p></div></details>
<h3 className="experience-group leadership-heading">Leadership &amp; community</h3>
<article className="experience-entry"><header><div><h3>President</h3><p className="mono">Engineering Student Council · UT Arlington</p></div><span className="role-date mono">May 2025 to present</span></header><ul><li>I lead 26 officers and coordinate with 33 engineering student organizations.</li><li>I managed a $13,000 budget that funded 14 Engineers Week events.</li><li>I helped bring Bell Helicopter to campus for a live helicopter landing.</li><li>Cross-organization participation grew by 40% compared with the previous year.</li></ul></article>
<article className="experience-entry"><header><div><h3>President</h3><p className="mono">Datathon UTA</p></div><span className="role-date mono">April 2025 to present</span></header><ul><li>I lead a 48-person team across the event’s technical and operational work.</li><li>The competition drew 440 registrations and 311 event-day check-ins.</li><li>I secured three sponsors and $12,500 in funding.</li><li>I coordinated 12 mentors and judges alongside five workshops.</li></ul></article>
<article className="experience-entry"><header><div><h3>Founder, President and Captain</h3><p className="mono">Dastaan Bollywood Fusion Dance Team · UT Arlington</p></div><span className="role-date mono">August 2025 to May 2026</span></header><ul><li>I started UTA’s first competitive Bollywood fusion dance team.</li><li>We recruited 40 members and built an eight-person leadership team.</li><li>We put on eight performances for more than 1,000 total attendees.</li><li>I handled recruiting, tryouts, performance planning, and campus partnerships.</li></ul></article>
<article className="experience-entry"><header><div><h3>Founder and President</h3><p className="mono">Students in Computing and Artificial Intelligence · UT Arlington</p></div><span className="role-date mono">February 2024 to May 2025</span></header><ul><li>I founded SCAI and grew it to more than 500 members.</li><li>With a 15-officer team, we ran about 30 events and workshops.</li><li>General meetings averaged 70+ attendees.</li></ul></article>
<details className="role-dropdown"><summary className="mono">SHOW MORE LEADERSHIP <span>+</span></summary><div className="more-role-list"><p><strong>Vice President, Engineering Student Council</strong><br/>Helped plan engineering events and coordinate communication across clubs and campus partners.</p><p><strong>Vice President, Datathon UTA</strong><br/>Supported sponsor coordination, schedules, internal workflows, and event-day planning.</p><p><strong>Board of Directors, NAESC</strong><br/>Worked with engineering student leaders across the country on governance and programming.</p><p><strong>inSTEM Scholar</strong><br/>Joined a national cohort focused on STEM leadership, mentorship, and advocacy.</p></div></details>
<div className="certifications"><h3>CERTIFICATIONS</h3><div className="credentials"><a href="https://www.credly.com/badges/5d7d4de0-8ea4-4788-8817-a51f97c09c57/public_url" target="_blank" rel="noreferrer"><span>Professional Scrum Product Owner I (PSPO I)</span><small className="mono">Scrum.org · May 2026</small><ArrowUpRight size={18}/></a><a href="https://www.credly.com/badges/3790d364-b419-448a-b7f9-1389109ec5d2/public_url" target="_blank" rel="noreferrer"><span>Product Management Essentials</span><small className="mono">IBM Developer Skills Network / Coursera · December 2025</small><ArrowUpRight size={18}/></a><a href="https://www.credly.com/badges/eb74c9d2-5e88-4e30-9203-1cefaeaf1026/public_url" target="_blank" rel="noreferrer"><span>AWS Academy Graduate: Cloud Architecting</span><small className="mono">AWS training badge · December 2025</small><ArrowUpRight size={18}/></a><a href="https://www.credly.com/badges/f51eab62-23a1-4aad-bd43-a33ae123da04/public_url" target="_blank" rel="noreferrer"><span>AWS Academy Graduate: Cloud Data Pipeline Builder</span><small className="mono">AWS training badge · October 2025</small><ArrowUpRight size={18}/></a><a href="https://www.credly.com/badges/c2dc4a19-2a0b-4e30-9203-1cefaeaf1026/public_url" target="_blank" rel="noreferrer"><span>AWS Academy Graduate: Cloud Security Builder</span><small className="mono">AWS training badge · November 2025</small><ArrowUpRight size={18}/></a><a href="https://www.credly.com/badges/5dfe7762-8ac8-4f65-8d8f-c50de22eb747/public_url" target="_blank" rel="noreferrer"><span>AWS Academy Graduate: Microservices and CI/CD Pipeline Builder</span><small className="mono">AWS training badge · November 2025</small><ArrowUpRight size={18}/></a></div></div></section><section id="contact" className="contact"><div className="section-heading"><span className="mono">05.</span><h2>LET’S CONNECT</h2><span className="meta mono">BASED IN DALLAS-FORT WORTH</span></div><div className="contact-grid"><div className="contact-links"><a href="mailto:thesamarthjagtap@gmail.com"><Mail size={22}/><span>thesamarthjagtap@gmail.com</span></a><a href="https://www.linkedin.com/in/thesamarthjagtap/" target="_blank" rel="noreferrer"><BriefcaseBusiness size={22}/><span>linkedin.com/in/thesamarthjagtap</span></a><a href="https://github.com/thatscrazzyy" target="_blank" rel="noreferrer"><Code size={22}/><span>github.com/thatscrazzyy</span></a><p className="mono">EMAIL ME ABOUT A ROLE,<br/>A PROJECT, OR SOMETHING YOU’RE BUILDING. <ArrowUpRight size={17}/></p></div><a className="contact-art" href="mailto:thesamarthjagtap@gmail.com"><p className="mono">LET’S<br/>TALK<br/>ABOUT<br/>YOUR IDEA.</p><ArrowUpRight size={25}/></a></div></section><footer><a className="wordmark" href="#top">SAMARTH</a><span className="footer-rule"/><p className="mono">SOFTWARE ENGINEERING · UT ARLINGTON · CLASS OF 2026</p><i className="barcode"/><span className="mono">EST. 2026</span></footer>
</main>}
