import Motion from './motion';
import { ArrowDown, ArrowUpRight, ArrowRight, Crosshair, Globe2, Mail, Code, BriefcaseBusiness } from 'lucide-react';
const projects = [
  {name:'QuickDrop',image:'/images/quickdrop-orbit.webp',description:'Secure, session-based file transfers across AWS and GCP. 500 MB delivered in about 50 seconds on local Wi-Fi.',tags:['FULL STACK','AWS / GCP'],href:'https://quickdrop-9a015.web.app/'},
  {name:'UTA Datathon',image:'/images/datathon-base.webp',description:'Registration, QR check-in, and analytics for 400+ participants. From a minute in line to a 10-second check-in.',tags:['NEXT.JS','FIREBASE'],href:'https://famous-lily-a54f63.netlify.app/'},
  {name:'Map Daddy',image:'/images/map-daddy-lander.webp',description:'A web-controlled projection mapping system. Raspberry Pi rendering, multi-point geometry, and live visual control.',tags:['RASPBERRY PI','CREATIVE TECH'],href:'https://github.com/thatscrazzyy/map-daddy'},
];
export default function Home(){return <main id="top" className="portfolio"><Motion/>
<a className="skip-link" href="#projects">Skip to projects</a>
<section className="hero"><img className="hero-image" src="/images/space-background.webp" alt="" fetchPriority="high" width="3240" height="5760"/><div className="hero-scene"><img className="astronaut-layer" src="/images/astronaut-layer.webp" alt="An astronaut tethered to a spacecraft, floating in space" width="3240" height="5760"/></div>
<nav aria-label="Main navigation"><a className="wordmark" href="#top">SAMARTH</a><div className="nav-links"><a href="#top">HOME</a><a href="#about">ABOUT</a><a href="#projects">PROJECTS</a><a href="#experience">EXPERIENCE</a><a href="#contact">CONTACT</a></div><Crosshair className="nav-mark" size={30}/></nav>
<div className="hero-content"><p className="hero-kicker mono">SOFTWARE · SOLUTIONS · STORIES</p><h1><span>SAMARTH</span><span>JAGTAP.</span></h1><p className="intro">I turn complicated problems into<br className="desktop-break"/> useful software. And good stories.</p><p className="hero-description mono">A TECHNICAL BUILDER WITH PRODUCT INSTINCTS.<br/>CURIOUS ABOUT PEOPLE, SYSTEMS,<br/>AND WHAT HAPPENS WHEN THEY CONNECT.</p><a className="scroll-link mono" href="#projects"><ArrowDown size={28} strokeWidth={1}/><span>SCROLL TO<br/>EXPLORE THE WORK</span></a></div><span className="hero-note mono">SAME CHAOS.<br/>BIGGER IDEAS.<span className="plus">＋</span></span>
</section><div className="status-strip mono"><Globe2 size={28}/><span><small>CURRENTLY:</small>BUILDING COOL THINGS.</span><span className="location"><small>BASED IN:</small>DALLAS–FORT WORTH, TX</span><i className="barcode" aria-hidden="true"/></div>
<section id="projects" className="projects"><div className="eyebrow mono"><span>01.</span><a href="https://github.com/thatscrazzyy" target="_blank" rel="noreferrer">VIEW GITHUB <ArrowRight size={16}/></a></div><h2 className="featured-title">FEATURED PROJECTS</h2><div className="project-list">{projects.map((p,i)=><a key={p.name} className={'project project-'+i} href={p.href} target="_blank" rel="noreferrer"><span className="project-number mono">0{i+1}</span><div className="project-art"><img src={p.image} alt="" loading="lazy" width="1536" height="1024"/><span className="art-cross">+</span></div><div className="project-info"><h3>{p.name}</h3><p className="mono">{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div><ArrowUpRight className="project-arrow" size={29} strokeWidth={1.5}/></a>)}</div></section>
<section className="selected-work" id="selected-work"><div className="section-heading"><span className="mono">02.</span><h2>MORE EXPLORATIONS</h2><a className="meta mono" href="https://github.com/thatscrazzyy" target="_blank" rel="noreferrer">MORE PROJECTS <ArrowRight size={15}/></a></div><div className="work-grid">
<a href="https://igvc-web.vercel.app/" target="_blank" rel="noreferrer" className="work-tile"><div className="tile-image lunar"/><h3 className="mono">01. AUTONOMY</h3><p className="mono">ROBOTICS / VISION</p></a>
<a href="https://github.com/thatscrazzyy/map-daddy" target="_blank" rel="noreferrer" className="work-tile"><div className="tile-image red"/><h3 className="mono">02. MAP DADDY</h3><p className="mono">CREATIVE TECHNOLOGY</p></a>
<a href="https://quickdrop-9a015.web.app/" target="_blank" rel="noreferrer" className="work-tile"><div className="tile-image closeup"/><h3 className="mono">03. QUICKDROP</h3><p className="mono">CLOUD / FULL STACK</p></a>
<a href="#sidequest" className="work-tile"><div className="tile-image green"/><h3 className="mono">04. SIDEQUEST</h3><p className="mono">iOS / SOCIAL PLAY</p></a>
</div><details id="sidequest" className="sidequest"><summary className="mono">SIDEQUEST — AN EXPERIMENT IN SPONTANEITY <span>+</span></summary><p>A working iMessage-first prototype that turns everyday plans into quests between friends. Built with Swift, UIKit, and Firebase, with real-time updates and five quest states. Tested with 10 friends. Public release is still ahead.</p></details></section>
<div className="quote-strip"><div><span className="quote-mark">”</span><p className="mono">A LITTLE CURIOSITY.<br/>A LOT OF MAKING.<br/><br/>SOMEWHERE BETWEEN<br/>THE SYSTEMS WE BUILD<br/>AND THE STORIES<br/>WE TELL.</p></div><div className="quote-image"/><p className="mono quote-aside">IDEAS<br/>CODE<br/>PEOPLE<br/>SYSTEMS<br/>AND<br/>BEYOND.<span>✧</span></p></div><section id="about" className="about"><div className="section-heading"><span className="mono">03.</span><h2>ABOUT</h2><span className="meta mono">PEOPLE × IDEAS × SYSTEMS</span></div><div className="about-body"><div className="about-art"/><div><h3>CURIOUS<br/>BY NATURE.</h3><p>I’m a software engineering senior at UT Arlington with a minor in commercial filmmaking.</p><p>I like the messy part of building: understanding what people need, figuring out the system, and making something they can actually use. My work spans cloud applications, AI agents, and tools for real operations.</p><p>I’m drawn to forward deployed and solutions engineering—where building, listening, and explaining matter equally. Outside the code: filmmaking, dance, and bringing communities together.</p><a className="outline-link mono" href="#experience">MY JOURNEY <ArrowRight size={18}/></a></div><div className="explore-panel"><span>✧</span><Globe2 size={65} strokeWidth={.6}/><p className="mono">EXPLORE<br/>LEARN<br/>BUILD</p></div></div></section>
<section id="experience" className="experience"><div className="section-heading"><span className="mono">04.</span><h2>THE JOURNEY SO FAR</h2><span className="meta mono">BUILDING WITH PURPOSE</span></div>
<details open><summary><div><h3>SOFTWARE / AI INTERN</h3><p className="mono">LAPENTON INC.</p></div><span className="mono">MAR 2026 — NOW</span><span className="expand">+</span></summary><p>Building tools that turn real business needs into working software. An inventory utility handling 200,000+ records, 45% faster queries, and roughly 15 hours of manual work saved each week.</p><p>Deployed MCP-powered agents into a live customer Odoo environment with scoped access, approvals, audit logging, and rollback. Helped deliver a legacy migration in four weeks against an estimated six-month timeline.</p></details>
<details><summary><div><h3>TEACHING ASSISTANT</h3><p className="mono">UT ARLINGTON · COLLEGE OF ENGINEERING</p></div><span className="mono">AUG 2025 — NOW</span><span className="expand">+</span></summary><p>Supporting approximately 400 engineering students each semester. Automated grading workflows with Python to process 400 assignments in under four minutes.</p></details>
<details><summary><div><h3>COMMUNITIES, BUILT TOGETHER</h3><p className="mono">ENGINEERING STUDENT COUNCIL · DATATHON UTA</p></div><span className="expand">+</span></summary><p>President of UTA’s Engineering Student Council, coordinating 26 officers and 33 engineering organizations. Leading a 48-person Datathon team and helping bring 300+ active participants together.</p><p>Previously founded SCAI, growing it to 500+ members, and Dastaan, UTA’s first competitive Bollywood fusion dance team.</p></details>
<div className="credentials"><span className="mono">PSPO I · SCRUM.ORG</span><span className="mono">AWS ACADEMY · CLOUD ARCHITECTING</span><span className="mono">IBM · PRODUCT MANAGEMENT ESSENTIALS</span></div><div className="education mono">B.S. SOFTWARE ENGINEERING · UT ARLINGTON<br/><span>MINOR IN COMMERCIAL FILMMAKING · DEC 2026</span></div>
</section>
<section id="contact" className="contact"><div className="section-heading"><span className="mono">05.</span><h2>LET’S CONNECT</h2><span className="meta mono">SAME PLANET. DIFFERENT PERSPECTIVES.</span></div><div className="contact-grid"><div className="contact-links"><a href="mailto:thesamarthjagtap@gmail.com"><Mail size={22}/><span>thesamarthjagtap@gmail.com</span></a><a href="https://www.linkedin.com/in/thesamarthjagtap/" target="_blank" rel="noreferrer"><BriefcaseBusiness size={22}/><span>linkedin.com/in/thesamarthjagtap</span></a><a href="https://github.com/thatscrazzyy" target="_blank" rel="noreferrer"><Code size={22}/><span>github.com/thatscrazzyy</span></a><p className="mono">HAVE SOMETHING IN MIND?<br/>LET’S MAKE IT INTERESTING. <ArrowUpRight size={17}/></p></div><a className="contact-art" href="mailto:thesamarthjagtap@gmail.com"><p className="mono">TOMORROW<br/>LOOKS<br/>BRIGHTER<br/>FROM HERE.</p><ArrowUpRight size={25}/></a></div></section><footer><a className="wordmark" href="#top">SAMARTH</a><span className="footer-rule"/><p className="mono">GOOD SOFTWARE FOR A MORE INTERESTING TOMORROW.</p><i className="barcode"/><span className="mono">EST. 2026</span></footer>
</main>}
